--liquibase formatted sql
--changeset Vijay:V3.0
CREATE TABLE IF NOT EXISTS WORKFLOW (
WORKFLOW_ID BIGINT(19) auto_increment primary key,
CREATE_DATETIME TIMESTAMP,
LASTUPDATE_DATETIME TIMESTAMP,
STATUS INTEGER(10),
WORKFLOW_TEMPLATE_ID BIGINT(19)
);
--rollback DROP TABLE WORKFLOW

--changeset Vijay:V3.1
CREATE TABLE IF NOT EXISTS WORKFLOW_SETUP (
TEMPLATE_ID BIGINT(19) auto_increment primary key,
CREATE_DATETIME TIMESTAMP,
DESCRIPTION VARCHAR(255),
NAME VARCHAR(255)
);
--rollback DROP TABLE WORKFLOW_SETUP

--changeset Vijay:V3.2
CREATE TABLE IF NOT EXISTS WORKFLOW_WORKITEM_LINKS (
ID BIGINT(19) auto_increment primary key,
IS_START_WORKITEM BOOLEAN(1),
NEXT_WORKITEM_TEMPLATE_ID BIGINT(19),
WORKFLOW_TEMPLATE_ID BIGINT(19),
WORKITEM_TEMPLATE_ID BIGINT(19)
);
--rollback DROP TABLE WORKFLOW_WORKITEM_LINKS

--changeset Vijay:V3.3
CREATE TABLE IF NOT EXISTS WORKITEM (
WORKITEM_ID BIGINT(19) auto_increment primary key,
CREATE_DATETIME TIMESTAMP,
LASTUPDATE_DATETIME TIMESTAMP,
STATUS VARCHAR(255),
WORKFLOW_ID BIGINT(19),
WORKITEM_TEMPLATE_ID BIGINT(19)
);
--rollback DROP TABLE WORKITEM

--changeset Vijay:V3.4
CREATE TABLE IF NOT EXISTS WORKITEM_ATTRIBUTE_SETUP (
ID BIGINT(19) auto_increment primary key,
ATTRIBUTE_NAME VARCHAR(255),
ATTRIBUTE_VALUE VARCHAR(255),
WORKITEM_TEMPLATE_ID BIGINT(19)
);
--rollback DROP TABLE WORKITEM_ATTRIBUTE_SETUP

--changeset Vijay:V3.5
CREATE TABLE IF NOT EXISTS WORKITEM_SETUP (
TEMPLATE_ID BIGINT(19) auto_increment primary key,
CLASS_NAME VARCHAR(255),
IS_RERUNNABLE BOOLEAN(1),
NAME VARCHAR(255),
NEXT_WORKITEM_TEMPLATE_ID BIGINT(19),
WORKITEM_TEMPLATE_ID BIGINT(19)
);
--rollback DROP TABLE WORKITEM_SETUP

